### ISSUE TITLE
Add support for DUPLICATE_POLICY on TS.CREATE/TS.ALTER and TS.ADD

### ISSUE THREAD

**Issue by filipecosta90** [nikolovskimilos/redistimeseries-js#17]
As of RedisTimeseries >= 1.4 You can now add samples to a time series where the time of the sample is older than the newest sample in the series. Bundled with that, we now have a policy that will define handling of duplicate samples, and that needs to be supported on the client via the arguments `[DUPLICATE_POLICY policy]` on `TS.CREATE` and via `[ON_DUPLICATE policy]` on `TS.ADD`. The following are the possible policies:

* `BLOCK` - an error will occur for any out of order sample
* `FIRST` - ignore the new value
* `LAST` - override with latest value
* `MIN` - only override if the value is lower than the existing value
* `MAX` - only override if the value is higher than the existing value

Further reference: [documentation link](https://oss.redislabs.com/redistimeseries/master/configuration/#duplicate_policy)

**Comment by willCode2Surf** [comment]
👍 This would be fantastic and we need this in the library!

**Comment by dashaun** [comment]
FYI - I'm working on this issue now!  I have a fork that works for me, and I'm working on a clean PR right now, with help from @WoodyDark !!!

https://github.com/dashaun/redistimeseries-js

**Comment by nikolovskimilos** [comment]
Sorry for the late response

Thanks a lot @dashaun, I have merged your changes
I am going to do some adjustments and publish new version

**Comment by dashaun** [comment]
@nikolovskimilos You are amazing!  I had help creating this PR

https://youtu.be/UXjrB2Fzb1A

**Comment by nikolovskimilos** [comment]
#19

**Comment by nikolovskimilos** [comment]
New version is published [2.2.0](https://www.npmjs.com/package/redistimeseries-js/v/2.2.0)
